name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build & Release
    runs-on: windows-latest
    env:
      SOLUTION_FILE: Engine.sln
      EDITOR: Editor/Editor.csproj
      DIST_DIR: dist

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Add MikkTSpace
        run: git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/mmikk/MikkTSpace.git packages/MikkTSpace

      - name: Download and extract FBX SDK
        run: |
          $url = 'https://drive.usercontent.google.com/download?id=1dIRXQ8U8Pjk46p5yAZy8NV-UPtT0utZu&export=download&authuser=0&confirm=t&uuid=780e7af0-71a7-40cb-92a4-da1f27aaf7a7&at=AN8xHop1oRwI7kHy5S5dObJuMOLc%3A1753290243197'
          Invoke-WebRequest -Uri $url -OutFile 'FBX SDK.zip'
          Expand-Archive -Path 'FBX SDK.zip' -DestinationPath 'packages/FBX SDK'

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore ${{ env.SOLUTION_FILE }}

      - name: Setup MSBuild
        run: |
          $msbuildPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" `
            -version '[18.0,19.0)' -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe | Select-Object -First 1
          Write-Host "Found MSBuild at: $msbuildPath"
          Add-Content -Path $env:GITHUB_PATH -Value (Split-Path $msbuildPath)

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'

      - name: Restore .NET packages
        run: dotnet restore ${{ env.EDITOR }}

      - name: Publish Editor
        run: |
          dotnet publish ${{ env.EDITOR }} `
            --configuration ReleaseEditor `
            --runtime win-x64 `
            --self-contained true `
            --output ${{ env.DIST_DIR }} `
            -p:PublishSingleFile=true `
            -p:SatelliteResourceLanguages=en-US

      - name: Build Solution
        run: msbuild ${{ env.SOLUTION_FILE }} /p:Configuration=ReleaseEditor /p:Platform=x64 /m

      - name: Copy Engine binaries
        run: |
          $src = "x64\ReleaseEditor"
          $dst = "${{ env.DIST_DIR }}"
          'dxcompiler.dll', 'dxil.dll', 'ContentTools.dll', 'EngineDLL.dll', 'EngineDLL.lib', 'Engine.lib' | ForEach-Object {
            Copy-Item "$src\$_" -Destination $dst -Force
          }
          Copy-Item "$src\D3D12" -Destination $dst -Recurse -Force
          
          New-Item -ItemType Directory -Path "$dst\Engine\x64\ReleaseEditor" -Force | Out-Null
          Copy-Item "Engine\x64\ReleaseEditor\Engine.lib" "$dst\Engine\x64\ReleaseEditor" -Force
          Copy-Item "Engine\x64\ReleaseEditor\Engine.pdb" "$dst\Engine\x64\ReleaseEditor" -Force

      - name: Copy Headers and Shaders
        run: |
          robocopy Engine ${{ env.DIST_DIR }}\Engine *.h *.hlsl *.hlsli /E
          if ($LASTEXITCODE -lt 8) { exit 0 } else { exit $LASTEXITCODE }

      - name: Copy meta files
        run: Copy-Item 'Changelog.md', 'LICENCE.md', 'README.md' -Destination ${{ env.DIST_DIR }} -Force

      - name: Restore Wix packages
        run: |
          dotnet restore Installer/Installer.wixproj
          dotnet restore Bundle/Bundle.wixproj

      - name: Get Version Info
        id: get-version
        run: |
          [xml]$proj = Get-Content ${{ env.EDITOR }}
          $asmVersion = $proj.SelectSingleNode("//AssemblyVersion").InnerText.Trim()
          $infoVersion = $proj.SelectSingleNode("//InformationalVersion").InnerText.Trim()
          Add-Content -Path $env:GITHUB_OUTPUT -Value "ASSEMBLY_VERSION=$asmVersion"
          Add-Content -Path $env:GITHUB_OUTPUT -Value "INFO_VERSION=$infoVersion"

      - name: Build Installer and Bundle
        run: |
          msbuild Installer/Installer.wixproj /p:Configuration=Release /p:Platform=x64 /p:PublishedDir="$env:GITHUB_WORKSPACE\dist" /p:Version="${{ steps.get-version.outputs.ASSEMBLY_VERSION }}" /m
          msbuild Bundle/Bundle.wixproj /p:Configuration=Release /p:Platform=x64 /p:PublishedDir="$env:GITHUB_WORKSPACE\dist" /p:Version="${{ steps.get-version.outputs.ASSEMBLY_VERSION }}" /m

      - name: Get Release notes
        id: get-release-notes
        shell: bash
        run: |
          sed -n '0,/^# v/!d; /^# v/p; :a; n; /^# v/q; p; ba' Changelog.md > release-notes.md
          echo "body<<EOF" >> $GITHUB_OUTPUT
          cat release-notes.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Zip distribution
        run: Compress-Archive -Path ${{ env.DIST_DIR }}\* -DestinationPath "lightning-engine-v${{ steps.get-version.outputs.INFO_VERSION }}.zip" -Force

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get-version.outputs.INFO_VERSION }}
          name: v${{ steps.get-version.outputs.INFO_VERSION }}
          body: ${{ steps.get-release-notes.outputs.body }}
          draft: false
          prerelease: true
          files: |
            lightning-engine-v${{ steps.get-version.outputs.INFO_VERSION }}.zip
            Bundle/bin/x64/Release/Lightning-Setup.exe
            Installer/bin/x64/Release/en-US/Lightning-Installer.msi
